apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-namespace
  namespace: dev
  labels:
    app: nginx
    tier: frontend
    version: 1.2.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      name: myapp-namespace
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0-latest
        

