apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-frontend
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      - name: nginx
        images: nginx
  replicas: 3
  selector:
    matchLabels:
      app: myapp