# then you implement the certificate security. you can input the certificate in every command to verifay your self in k8s.
  # there is an bater soltuion to put these all certificate command in one  

# create the config file,
  # $home/.kube/config
    # {
       --server my-kube-playgroung:6443
       --client-key admin.key
       --client-certificate admin.crt
       --certificate-authority ca.crt
       
       }

# config file had the 3 new sections:
  # clusters
  # contexts
  # users


apiVersion: v1
kind: config

clusters:
  - name: my-kube-playgroud
    cluster:
      certification-authority: ca.crt
      server: http://my-kube-playground:6443

contexts:
  - name: my-kube-admin@my-kube-playgroud
  contexts:
    cluster: my-kube-playgroud
    user: my-kube-admin

users:
  - name: my-kube-admin
    user:
      client-certificate: admin.crt
      --client-key: admin.key


# some important config commands.
kubctl config view
kubctl config view --kubeconfig=my-costome-config
kubctl config use-context prod-user@production
kubctl config -h 



## always incoded the certificate file and use them in the config.
cat ca.crt | base64
 #and decond the file by the command
echo "<CODE-FILE>" | base64 --decode







